#
# Sera - OnePage Jekyll Template
# Configuration File
#

# Information for compile
exclude: ["node_modules", "gulpfile.js", "package.json", "Gemfile", "README.md"]

#
# If your website is placed in a separate folder on your server please modify
# this with your folder name, by default is empty.
# Example: Sera Demo is hosted on projects.gleesik.ro/sera-onepage
# If I compile Sera Template and I put in /sera-onepage without modifing baseurl
# than scripts can't be loaded corectly.
# For this example my site url is: projects.gleesik.ro (This can be just www.example.com)
# My folder for Demo Website is: /sera-onepage so baseurl: /sera-onepage
#
baseurl: 

# the base hostname & protocol for your site
url: "https://sshao0516.github.io/CrowdHuman/"

####################################
######   Optional Features    ######
####################################
smooth-scroll: false

####################################
###########   Plugins    ###########
####################################
plugins:
#  - jekyll-archives # Sorry, not GitHub pages friendly!

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

# This is your site title
title: CrowdHuman Dataset
# Website language
lang: en-US
# Header Title
header-title: A Benchmark for Detecting Human in a Crowd
# Header Tagline
headter-tagline: CrowdHuman

####################################
######  Global Social Links   ######
####################################
youtube: '#'
pinterest: '#'
facebook: '#'
twitter: '#'
google-plus: '#'
vimeo: '#'

#####################################
#############   About   #############
#####################################
overview-title: Overview
overview-description: CrowdHuman is a benchmark dataset to better evaluate detectors in crowd scenarios. The CrowdHuman dataset is large, rich-annotated and contains high diversity. CrowdHuman contains 15000, 4370 and 5000 images for training, validation, and testing, respectively. There are a total of 470K human instances(339565 unique) from train and validation subsets and 23 persons per image, with various kinds of occlusions in the dataset. Each human instance is annotated with a head bounding-box, human visible-region bounding-box and human full-body bounding-box. We hope our dataset will serve as a solid baseline and help promote future research in human detection tasks. 


#####################################
#############  Features  ############
#####################################
features-title: Features
features-description: For details on the CrowdHuman dataset please refer to the paper.

#
# Features
#
features:

# Feature
- title: More Crowded
  description: More Corwded
  icon: pe-7s-vector

# Feature
- title: Three Box
  description: Three Box
  icon: pe-7s-help2

# Feature
- title: Bigger
  description: Bigger
  icon: pe-7s-airplay


#####################################
############  Portfolio  ############
#####################################
portfolio-title: Explore
portfolio-description: Some examples.

#
# Portfolio Grid
#
portfolio-categories: [Head BBox, Vis BBox, Full BBox]
portfolio:

# Portfolio Item
- title: example
  categories: [Head BBox]
  image: 1.jpg
  url: '#'

# Portfolio Item
- title: example
  categories: [Vis BBox]
  image: 2.jpg
  url: '#'

# Portfolio Item
- title: example
  categories: [Full BBox]
  image: 3.jpg
  url: '#'

# Portfolio Item
- title: example
  categories: []
  image: 4.jpg
  url: '#'

# Portfolio Item
- title: example
  categories: []
  image: 5.jpg
  url: '#'

# Portfolio Item
- title: example
  categories: []
  image: 6.jpg
  url: '#'

# Portfolio Item
- title: example
  categories: []
  image: 7.jpg
  url: '#'

# Portfolio Item
- title: example
  categories: []
  image: 8.jpg
  url: '#'

# Portfolio Item
- title: example
  categories: []
  image: 9.jpg
  url: '#'


#####################################
##########  Core Features  ##########
#####################################
core-title: Challenge
core-description: Opening in the future...

#####################################
############  Download  #############
#####################################
download-title: Download
download-description: 1234567890

#####################################
#############  License   ############
#####################################
license-title: License
license-description: 

#####################################
############### Team ################
#####################################
team-title: Meet Our Team
team-description: Detection team of Megvii Research.

#
# Team Members
#
team:

# Team Member
- name: Shuai Shao
  tagline: Researcher
  avatar: avatar-01.jpg

  # Social Links
  youtube: '#'
  pinterest: '#'
  facebook: '#'
  twitter: '#'
  google-plus: '#'
  vimeo: '#'

# Team Member
- name: Zijian Zhao
  tagline: Research Intern
  avatar: avatar-02.jpg

  # Social Links
  youtube: '#'
  pinterest: '#'
  facebook: '#'
  twitter: '#'
  google-plus: '#'
  vimeo: '#'

# Team Member
- name: Boxun Li
  tagline: Researcher
  avatar: avatar-04.jpg

  # Social Links
  youtube: '#'
  pinterest: '#'
  facebook: '#'
  twitter: '#'
  google-plus: '#'
  vimeo: '#'

# Team Member
- name: Tete Xiao
  tagline: Research Intern
  avatar: avatar-03.jpg

  # Social Links
  youtube: '#'
  pinterest: '#'
  facebook: '#'
  twitter: '#'
  google-plus: '#'
  vimeo: '#'

# Team Member
- name: Gang Yu
  tagline: Leader of Detection team
  avatar: 

  # Social Links
  youtube: '#'
  pinterest: '#'
  facebook: '#'
  twitter: '#'
  google-plus: '#'
  vimeo: '#'

# Team Member
- name: Xiangyu Zhang
  tagline: Leader of Basemodel Team
  avatar: 

  # Social Links
  youtube: '#'
  pinterest: '#'
  facebook: '#'
  twitter: '#'
  google-plus: '#'
  vimeo: '#'

# Team Member
- name: Jian Sun
  tagline: Managing Director of Research (Chief Scientist)
  avatar: 

  # Social Links
  youtube: '#'
  pinterest: '#'
  facebook: '#'
  twitter: '#'
  google-plus: '#'
  vimeo: '#'


#####################################
############# Our Blog ##############
#####################################
blog-title: Our Blog
blog-description: Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.


#####################################
############   Contact   ############
#####################################
contact-title: Contact Us
contact-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat.


#####################################
#############   Footer   ############
#####################################
footer-description: Power Human with AI.
footer-copyright-text: Megvii Inc. (Face++)
footer-copyright-url: http://www.megvii.com
footer-copyright-year: 2018
